name: LyttleScoreboardEconomy
version: '${projectVersion}'
main: com.lyttldev.lyttlescoreboardeconomy.LyttleScoreboardEconomy
api-version: '1.20'
author: LyttlDev
depend:
  - Vault
loadbefore:
  - LyttleEssentials

commands:
  tokens:
    usage: /tokens
    description: A command
  baltop:
    usage: /baltop
    description: A command

