name: LyttleScoreboardEconomy
description: A lightweight economy plugin that uses scoreboard objectives to store data.
version: '${projectVersion}'
main: com.lyttldev.lyttlescoreboardeconomy.LyttleScoreboardEconomy
api-version: '1.21'
authors:
  - LyttleDevelopment
  - ThatsATim
  - Stualyttle

depend:
  - Vault
loadbefore:
  - LyttleEssentials

commands:
  tokens:
    usage: /tokens
    description: A command

  baltop:
    usage: /baltop
    description: A command
    permission: lyttleeconomyscoreboard.baltop

  lyttlescoreboardeconomy:
    usage: /lyttlescoreboardeconomy [reload]
    description: Admin command, mainly reload the config without the rest of the server
    permission: lyttlescoreboardeconomy.lyttlescoreboardeconomy